# Generated by Django 6.0.3 on 2026-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_city_service_alter_contact_mobile_seopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seopage',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='seopage',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='seopage',
            name='h1',
        ),
        migrations.RemoveField(
            model_name='seopage',
            name='published',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
