# Generated by Django 6.0.4 on 2026-06-02 09:46

from django.db import migrations, models


def seed_links(apps, schema_editor):
    InternalLink = apps.get_model('front', 'InternalLink')
    OutboundLink = apps.get_model('front', 'OutboundLink')

    internal_links = [
        ("SEO services", "/seo-services/", "seo"),
        ("website development", "/website-development/", "web"),
        ("social media marketing", "/social-media-marketing/", "social"),
        ("Google Ads management", "/google-ads-services/", "ads"),
        ("digital marketing services", "/digital-marketing-services/", "marketing"),
        ("contact our growth team", "/contact/", "general"),
        ("meet the INKAGROWTH team", "/team/", "general"),
    ]
    outbound_links = [
        ("Google Search Central", "https://developers.google.com/search", "seo"),
        ("Google Business Profile", "https://www.google.com/business/", "local"),
        ("Google Analytics", "https://analytics.google.com", "analytics"),
        ("Google Ads", "https://ads.google.com/home/", "ads"),
        ("Search Console", "https://search.google.com/search-console", "seo"),
        ("PageSpeed Insights", "https://pagespeed.web.dev", "performance"),
    ]

    for title, url, category in internal_links:
        InternalLink.objects.update_or_create(
            url=url,
            defaults={"title": title, "category": category},
        )

    for title, url, category in outbound_links:
        OutboundLink.objects.update_or_create(
            url=url,
            defaults={"title": title, "category": category},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_seopage_city_alter_seopage_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=80)),
            ],
            options={
                'ordering': ('category', 'title'),
            },
        ),
        migrations.CreateModel(
            name='OutboundLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('category', models.CharField(db_index=True, default='general', max_length=80)),
            ],
            options={
                'ordering': ('category', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SEOPageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('primary_keyword', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=160)),
                ('content_blocks', models.JSONField(blank=True, default=dict)),
                ('nearby_areas', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('service', 'city'),
                'constraints': [
                    models.UniqueConstraint(
                        fields=('service', 'city'),
                        name='unique_seo_page_template_service_city',
                    ),
                ],
            },
        ),
        migrations.RunPython(seed_links, migrations.RunPython.noop),
    ]
