# Generated by Django 6.0.4 on 2026-06-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_category_tag_authorprofile_mediafile_post_faq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='post',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='uploaded_by',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='front_post_status_ff355d_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='front_post_slug_317010_idx',
        ),
        migrations.RemoveField(
            model_name='seoanalysisresult',
            name='post',
        ),
        migrations.DeleteModel(
            name='SEOPage',
        ),
        migrations.RemoveConstraint(
            model_name='seopagetemplate',
            name='unique_seo_page_template_service_city',
        ),
        migrations.DeleteModel(
            name='SEOPageTemplate',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.DeleteModel(
            name='AuthorProfile',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='internal_links',
        ),
        migrations.RemoveField(
            model_name='post',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='outbound_links',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='twitter_image',
        ),
        migrations.DeleteModel(
            name='SEOAnalysisResult',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='InternalLink',
        ),
        migrations.DeleteModel(
            name='OutboundLink',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
