# Generated by Django 6.0.4 on 2026-06-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_remove_authorprofile_user_remove_faq_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('business_category', models.CharField(max_length=180)),
                ('location', models.CharField(max_length=180)),
                ('short_description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='portfolio/covers/')),
                ('client_logo', models.ImageField(blank=True, upload_to='portfolio/logos/')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], db_index=True, default='ongoing', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('services_provided', models.TextField(blank=True)),
                ('service_type', models.CharField(choices=[('google-maps-seo', 'Google Maps SEO'), ('social-media-management', 'Social Media Management'), ('meta-ads', 'Meta Ads'), ('website-development', 'Website Development'), ('branding', 'Branding'), ('lead-generation', 'Lead Generation'), ('local-seo', 'Local SEO'), ('complete-digital-marketing', 'Complete Digital Marketing')], db_index=True, max_length=40)),
                ('client_overview', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('work_done', models.TextField(blank=True)),
                ('keywords_targeted', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('before_inkagrowth', models.TextField(blank=True)),
                ('after_inkagrowth', models.TextField(blank=True)),
                ('keywords_targeted_count', models.PositiveIntegerField(blank=True, null=True)),
                ('search_visibility', models.CharField(blank=True, max_length=120)),
                ('profile_views', models.PositiveIntegerField(blank=True, null=True)),
                ('direction_requests', models.PositiveIntegerField(blank=True, null=True)),
                ('calls_received', models.PositiveIntegerField(blank=True, null=True)),
                ('leads_generated', models.PositiveIntegerField(blank=True, null=True)),
                ('campaigns_run', models.PositiveIntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('testimonial_text', models.TextField(blank=True)),
                ('testimonial_person_name', models.CharField(blank=True, max_length=140)),
                ('testimonial_person_designation', models.CharField(blank=True, max_length=160)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=180)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, upload_to='portfolio/og/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Project',
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ('display_order', '-updated_at', 'business_name'),
                'indexes': [models.Index(fields=['status', 'display_order'], name='front_portfolio_status_idx'), models.Index(fields=['service_type', 'status'], name='front_portfolio_service_idx'), models.Index(fields=['slug', 'status'], name='front_portfolio_slug_idx')],
            },
        ),
    ]
