"""
Django settings for inkagrowth project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TRUE_VALUES = {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'false').lower() in TRUE_VALUES

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'local-development-secret-key-for-inkagrowth-only-not-for-production-2026'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable is required when DJANGO_DEBUG is false.')




# Application definition

INSTALLED_APPS = [
    'front',
    'crm',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inkagrowth.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inkagrowth.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


ALLOWED_HOSTS = [
    "inkagrowth.com",
    "www.inkagrowth.com",
    ".onrender.com",
    "localhost",
    "127.0.0.1",
]

# settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = '/crm/login/'
LOGIN_REDIRECT_URL = '/crm/dashboard/'
LOGOUT_REDIRECT_URL = '/crm/login/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', str(not DEBUG)).lower() in TRUE_VALUES
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', str(not DEBUG)).lower() in TRUE_VALUES
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', str(not DEBUG)).lower() in TRUE_VALUES
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
X_FRAME_OPTIONS = 'DENY'


# Google Sheets lead sync
GOOGLE_SHEETS_CREDENTIALS_FILE = os.environ.get(
    'GOOGLE_SHEETS_CREDENTIALS_FILE',
    str(BASE_DIR / 'credentials' / 'credentials.json')
)
GOOGLE_SHEETS_SPREADSHEET_ID = os.environ.get(
    'GOOGLE_SHEETS_SPREADSHEET_ID',
    ''
)
GOOGLE_SHEETS_WORKSHEET_NAME = os.environ.get(
    'GOOGLE_SHEETS_WORKSHEET_NAME',
    'Leads'
)
GOOGLE_SHEETS_SYNC_ENABLED = (
    os.environ.get('GOOGLE_SHEETS_SYNC_ENABLED', 'true').lower() in TRUE_VALUES
    and bool(GOOGLE_SHEETS_SPREADSHEET_ID)
)


DATABASE_URL = os.environ.get('DATABASE_URL')

if not DATABASE_URL and not DEBUG:
    raise ImproperlyConfigured('DATABASE_URL environment variable is required when DJANGO_DEBUG is false.')

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '600')),
        conn_health_checks=True,
        ssl_require=os.environ.get('DB_SSL_REQUIRE', str(not DEBUG)).lower() in TRUE_VALUES,
    )
}


CSRF_TRUSTED_ORIGINS = [
    "https://inkagrowth.com",
    "https://www.inkagrowth.com",
]
